baseurl: '/'
permalink: pretty
title: 'FancyAI Lab'

description: 'Academic group website built with Jekyll Serif.'

logo:
  mobile: "images/logo/1.png"
  mobile_height: "38px"
  mobile_width: "38px"
  desktop: "images/logo/1.png"
  desktop_height: "48px"
  desktop_width: "160px"
  favicon: "images/logo/2.png"

home:
  featured_topics_limit: 4

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  topics:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
