
- date: 2023-08-01
  content: "Local Organizing Committee and Technical Program Committee of KSEM-2023."

- date: 2023-08-17
  content: "Reviewer of IEEE Transactions on Parallel and Distributed Systems (TPDS)."

- date: 2023-07-16
  content: "Reviewer of ACM MM."


# Add more news items here...